# Generated by Django 5.2.12 on 2026-04-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_otplogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPLogin',
        ),
    ]
